---
- name: Push SSH key and enable passwordless login
  hosts: all
  become: true
  vars:
    ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"  # Path to your public SSH key

  tasks:
    - name: Ensure the user has an .ssh directory
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Push SSH key to the server
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ ssh_key }}"

    - name: Ensure correct permissions on .ssh directory
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Ensure correct permissions on authorized_keys file
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh/authorized_keys
        state: file
        mode: '0600'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
