---
- name: Safely Update packages on Kubernetes nodes
  hosts: all
  serial: 1
  become: true
  become_user: root
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

      ## Hold linux-image-6.8.0-55-generic to prevent kernel upgrade
      ## if the server is an rke2 or kubeadm server
    - name: Check if RKE2 is installed so it might be a Kubernetes server
      ansible.builtin.stat:
        path: /var/lib/rancher/rke2/bin/
      register: rke2_installed
      changed_when: false

    - name: Check if kubeadm is installed so it might be a kubeadm server
      ansible.builtin.stat:
        path: /usr/bin/kubeadm
      register: kubeadm_installed
      changed_when: false

    - name: Hold linux-image-6.8.0-55-generic on RKE2 or kubeadm servers
      ansible.builtin.command: apt-mark hold linux-image-6.8.0-55-generic
      when: rke2_installed.stat.exists or kubeadm_installed.stat.exists

    - name: Upgrade all packages on servers
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

    - name: Autoremove unused packages
      ansible.builtin.apt:
        autoremove: true

    - name: Autoclean packages no longer available
      ansible.builtin.apt:
        autoclean: true

    - name: Check if a reboot is needed
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      changed_when: false

    - name: Check if RKE2 is installed so it might be a kubernetes server
      ansible.builtin.stat:
        path: /var/lib/rancher/rke2/bin/
      register: kubectl_file
      changed_when: false

    - name: RKE2 is found. This is an RKE2 kubernetes server
      ansible.builtin.debug:
        msg: "RKE2 is found. This is an RKE2 kubernetes server, running the kubernetes reboot tasks."
      when: kubectl_file.stat.exists
      changed_when: false

    - name: Include kubernetes node restarts tasks if needed
      vars:
        kubeconfig_path: /etc/rancher/rke2/rke2.yaml
      ansible.builtin.include_tasks: tasks/kubernetes_node_reboot.yaml
      when:
        - reboot_required_file.stat.exists
        - kubectl_file.stat.exists

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for maintenance"
        reboot_timeout: 600  # Adjust the timeout as needed
      when:
        - reboot_required_file.stat.exists
        - not kubectl_file.stat.exists
      changed_when: true
